"""绩效报告与可视化"""

from __future__ import annotations

import os
import re

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import quantstats as qstat

# 无图形界面环境使用 Agg 后端，避免 plt.show() 阻塞
if os.environ.get("DISPLAY") is None and os.name != "nt":
    matplotlib.use("Agg")

plt.rcParams["font.sans-serif"] = ["SimHei", "Arial Unicode MS", "DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False

# 输出目录
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# HTML 报告英文指标 -> 中文翻译映射
_METRIC_TRANSLATIONS: dict[str, str] = {
    "Risk-Free Rate": "无风险利率",
    "Time in Market": "市场持仓时间占比",
    "Cumulative Return": "累计收益率",
    "CAGR﹪": "年化收益率 (CAGR)",
    "Sharpe": "夏普比率",
    "Prob. Sharpe Ratio": "夏普比率概率",
    "Smart Sharpe": "智能夏普比率",
    "Sortino": "索提诺比率",
    "Smart Sortino": "智能索提诺比率",
    "Sortino/√2": "索提诺比率/√2",
    "Smart Sortino/√2": "智能索提诺/√2",
    "Omega": "欧米伽比率",
    "Max Drawdown": "最大回撤",
    "Max DD Date": "最大回撤日期",
    "Max DD Period Start": "回撤开始日期",
    "Max DD Period End": "回撤结束日期",
    "Longest DD Days": "最长回撤天数",
    "Volatility (ann.)": "年化波动率",
    "Calmar": "卡尔玛比率",
    "Skew": "偏度",
    "Kurtosis": "峰度",
    "Ulcer Performance Index": "溃疡绩效指数",
    "Risk-Adjusted Return": "风险调整收益",
    "Risk-Return Ratio": "风险收益比",
    "Avg. Return": "平均日收益",
    "Avg. Win": "平均盈利",
    "Avg. Loss": "平均亏损",
    "Win/Loss Ratio": "盈亏比",
    "Profit Ratio": "盈利比率",
    "Expected Daily": "预期日收益",
    "Expected Monthly": "预期月收益",
    "Expected Yearly": "预期年收益",
    "Kelly Criterion": "凯利准则",
    "Risk of Ruin": "破产风险",
    "Daily Value-at-Risk": "日风险价值 (VaR)",
    "Expected Shortfall (cVaR)": "预期亏损 (cVaR)",
    "Max Consecutive Wins": "最大连续盈利次数",
    "Max Consecutive Losses": "最大连续亏损次数",
    "Gain/Pain Ratio": "盈亏痛苦比",
    "Gain/Pain (1M)": "月度盈亏痛苦比",
    "Payoff Ratio": "收益比率",
    "Profit Factor": "盈利因子",
    "Common Sense Ratio": "常识比率",
    "CPC Index": "CPC 指数",
    "Tail Ratio": "尾部比率",
    "Outlier Win Ratio": "异常盈利比率",
    "Outlier Loss Ratio": "异常亏损比率",
    "MTD": "本月至今收益",
    "3M": "近3月收益",
    "6M": "近6月收益",
    "YTD": "年初至今收益",
    "1Y": "近1年收益",
    "3Y (ann.)": "近3年年化收益",
    "5Y (ann.)": "近5年年化收益",
    "10Y (ann.)": "近10年年化收益",
    "All-time (ann.)": "历史年化收益",
    "Best Day": "最佳单日",
    "Worst Day": "最差单日",
    "Best Month": "最佳单月",
    "Worst Month": "最差单月",
    "Best Year": "最佳年度",
    "Worst Year": "最差年度",
    "Avg. Drawdown": "平均回撤",
    "Avg. Drawdown Days": "平均回撤天数",
    "Recovery Factor": "恢复因子",
    "Ulcer Index": "溃疡指数",
    "Serenity Index": " serenity 指数",
    "Avg. Up Month": "平均上涨月收益",
    "Avg. Down Month": "平均下跌月收益",
    "Win Days": "盈利天数占比",
    "Win Month": "盈利月份占比",
    "Win Quarter": "盈利季度占比",
    "Win Year": "盈利年度占比",
    "Metric": "指标",
    "Strategy": "策略",
    "Year": "年份",
    "Return": "年度收益",
    "Cumulative": "累计收益",
    "Key Performance Metrics": "核心绩效指标",
    "EOY Returns": "年度收益",
    "Tearsheet (generated by QuantStats)": "策略回测报告",
    "Periods/Year": "每年交易日",
    "RF": "无风险利率",
    "Generated by": "生成工具",
    "Compounded": "复利计算",
    "Multiplier": "倍数",
    "Won": "胜负",
    "R^2": "R平方",
    "Information Ratio": "信息比率",
    "Beta": "贝塔",
    "Alpha": "阿尔法",
    "Started": "开始日期",
    "Recovered": "恢复日期",
    "Drawdown": "回撤幅度",
    "Days": "天数",
    "Worst 10 Drawdowns": "最差10次回撤",
}


def _translate_html_metrics(html_content: str) -> str:
    """将 HTML 报告中的英文指标名替换为中英对照"""
    # 按长度降序排序，避免短词先替换导致长词无法匹配
    for en, cn in sorted(_METRIC_TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True):
        # 匹配 <td> 或 <th> 标签内的英文文本，替换为中英对照
        # 使用 lambda 避免 group reference 问题
        pattern_td = re.compile(rf'(<td[^>]*>)({re.escape(en)})(</td>)')
        html_content = pattern_td.sub(lambda m: f"{m.group(1)}{en} ({cn}){m.group(3)}", html_content)

        pattern_th = re.compile(rf'(<th[^>]*>)({re.escape(en)})(</th>)')
        html_content = pattern_th.sub(lambda m: f"{m.group(1)}{en} ({cn}){m.group(3)}", html_content)

        # 匹配 h3 标题
        pattern_h3 = re.compile(rf'(<h3[^>]*>)({re.escape(en)})(</h3>)')
        html_content = pattern_h3.sub(lambda m: f"{m.group(1)}{en} ({cn}){m.group(3)}", html_content)
    return html_content


def performance_report(
    nav: pd.Series,
    benchmark: pd.Series | None = None,
    title: str = "策略回测报告",
) -> str:
    """输出 quantstats 回测报告并保存 HTML 到 output 目录（不自动打开浏览器）"""
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")

    # 使用 metrics 输出文字指标（避免 quantstats 图表兼容性问题）
    qstat.reports.metrics(nav, benchmark=benchmark, display=True)

    safe_title = title.replace(" ", "_").replace(":", "_")
    filename = f"{safe_title}.html"
    filepath = os.path.join(OUTPUT_DIR, filename)
    try:
        # output 传字符串路径，quantstats 会写入该文件
        qstat.reports.html(
            nav, benchmark=benchmark, title=title,
            output=filepath,
        )
        # 读取并翻译为中文
        with open(filepath, "r", encoding="utf-8") as f:
            html_content = f.read()
        html_content = _translate_html_metrics(html_content)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_content)
        print(f"\n[报告已保存] {filepath}")
    except Exception as e:
        print(f"\n[警告] HTML 报告生成失败: {e}")
    return filepath


def plot_nav_curves(
    results: dict[str, tuple[pd.DataFrame, list[str], str]],
    save_path: str | None = None,
) -> None:
    """
    绘制各策略的净值曲线（含标的对比）

    Parameters
    ----------
    results : dict
        {策略名: (data_df, name_list, strategy_nav_col)}
    save_path : str | None
        图片保存路径，None 则保存到 output 目录
    """
    if save_path is None:
        save_path = os.path.join(OUTPUT_DIR, "策略净值对比明细.png")

    n = len(results)
    fig, axes = plt.subplots(1, n, figsize=(8 * n, 6))
    if n == 1:
        axes = [axes]

    for ax, (strategy_name, (data, name_list, nav_col)) in zip(axes, results.items()):
        for name in name_list:
            nav = data[name] / data[name].iloc[0]
            ax.plot(nav.index, nav.values, linestyle="--", alpha=0.7, label=name)

        ax.plot(
            data[nav_col].index,
            data[nav_col].values,
            linestyle="-",
            color="#FF8124",
            linewidth=2,
            label="策略净值",
        )
        ax.set_xlabel("日期")
        ax.set_ylabel("净值")
        ax.legend(loc="upper left")
        ax.set_title(strategy_name)
        ax.grid(True, alpha=0.3)

    plt.suptitle("净值曲线对比", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[图表已保存] {save_path}")


def plot_strategy_comparison(
    nav_dict: dict[str, pd.Series],
    save_path: str | None = None,
    title: str = "多策略净值对比",
) -> None:
    """将多个策略的净值放在一张图中对比"""
    if save_path is None:
        save_path = os.path.join(OUTPUT_DIR, "策略净值对比.png")

    fig, ax = plt.subplots(figsize=(15, 7))
    colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b"]

    for i, (name, nav) in enumerate(nav_dict.items()):
        ax.plot(nav.index, nav.values, linestyle="-", color=colors[i % len(colors)],
                linewidth=2, label=name)

    ax.set_xlabel("日期")
    ax.set_ylabel("净值")
    ax.legend(loc="upper left")
    ax.set_title(title)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[图表已保存] {save_path}")


def print_summary(results: dict[str, pd.Series]) -> None:
    """打印各策略最终净值对比表"""
    print("\n" + "="*60)
    print("【最终净值对比】")
    print("="*60)
    summary = pd.DataFrame([
        {
            "策略": name,
            "最终净值": round(nav.iloc[-1], 4),
            "回测起点": str(nav.index[0]),
            "回测终点": str(nav.index[-1]),
        }
        for name, nav in results.items()
    ])
    print(summary.to_string(index=False))
    print("="*60)
